version: '3.8'
services:
  mysqldb:
    container_name: servermanager_db
    image: mysql
    ports:
      - "3307:3306"
    networks:
      - spring-boot-mysql-network
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=servermanagerapp
      - MYSQL_USER=user
      - MYSQL_PASSWORD=123456789
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u root -p${MYSQL_ROOT_PASSWORD}"]
      interval: 30s
      timeout: 10s
      retries: 5
  app:
    container_name: servermanager_app
    ports:
      - "8084:8084"
    build: .
    networks:
      - spring-boot-mysql-network
    depends_on:
      mysqldb:
        condition: service_healthy
networks:
  spring-boot-mysql-network:
    driver: bridge