spring:
  jpa:
    database: SQL_SERVER
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    jdbc-url: jdbc:mysql://localhost:3306/servermanagerapp?createDatabaseIfNotExist=true;
    username: user
    password: 123456789
server:
   port: 8084

#      spring:
#        datasource:
#          driver-class-name: com.mysql.jdbc.Driver
#          url: jdbc:mysql://localhost:3306/servermanagerapp?createDatabaseIfNotExist=true
#          username: user
#          password: 123456789
#        jpa:
#          hibernate:
#            ddl-auto: update
#          show-sql: true
#          database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#      server:
#        port: 8084
#
#      #  spring.datasource.url=jdbc:mysql://localhost:3306/servermanagerapp?createDatabaseIfNotExist=true
#      #  spring.datasource.username=root
#      #  spring.datasource.password=123456789
#      #  spring.jpa.show-sql=true
#      #  server.port=8084
#      #  spring.jpa.database=mysql
#      #  spring.jpa.hibernate.ddl-auto=update
#      #  spring.jpa.database-platform=org.hibernate.dialect.MySQL5InnoDBDialect
#
#